hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 16384
  train_batch_size: 512
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang_async
    #max_model_len: 16384
    multi_turn:
      enable: True
      max_turns: 5
      format: qwen
      # tool_config_path: "./config/tool_config/gsm8k_tool_config.yaml"
