hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 16384
  train_batch_size: 512
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_turns: 20
    val_kwargs:
      temperature: 0.6
      top_k: -1
      top_p: 0.95
      n: 1
      do_sample: True

trainer:
  log_val_generations: 20
  rollout_data_dir: /data/tensorboard/rollout
  validation_data_dir: /data/tensorboard/validation
  tool_logging:
    log_dir: /data/tensorboard/tool_logs
