tools:
  - class_name: "verl.tools.sandbox_fusion_tools.SandboxFusionTool"
    config:
      type: native
      sandbox_fusion_url: https://code-sandbox.ali-dev.modelbest.co 
      num_workers: 8192
      rate_limit: 8192
      mode: "sim_jupyter"  # run_code, run_jupyter, sim_jupyter
      default_timeout: 3
    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "Execute Python code to perform calculations, data analysis, or other computational tasks with ipykernel, which means before execution print also returns in new tool response."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The Python code to be executed. This can include calculations, data manipulation, or any valid Python code."
            language:
              type: "string"
              description: "The programming language of the code. Currently only Python is supported."
              default: "python"
          required: ["code"]
