tools:
  - class_name: "verl.tools.sandbox_fusion_tools.SandboxFusionTool"
    config:
      type: native
      sandbox_fusion_url: https://sd04qmtd8e6v9i08l9l00.apigateway-cn-beijing.volceapi.com
      num_workers: 8192
      rate_limit: 8192
      mode: "sim_jupyter"  # run_code, run_jupyter, sim_jupyter
      default_timeout: 3
    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "Execute Python code to perform calculations, data analysis, or other computational tasks."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The Python code to be executed. This can include calculations, data manipulation, or any valid Python code."
          required: ["code"]
